<?php

namespace Database\Seeders;
use App\Models\Tag;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tags = [
            [
                'cod' => 'vermelho',
                'cod_eng' => 'red',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'azul',
                'cod_eng' => 'blue',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'verde',
                'cod_eng' => 'green',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'amarelo',
                'cod_eng' => 'yellow',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'laranja',
                'cod_eng' => 'orange',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'roxo',
                'cod_eng' => 'purple',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'rosa',
                'cod_eng' => 'pink',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'cinza',
                'cod_eng' => 'gray',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'preto',
                'cod_eng' => 'black',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'branco',
                'cod_eng' => 'white',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'marrom',
                'cod_eng' => 'brown',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'bege',
                'cod_eng' => 'beige',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'turquesa',
                'cod_eng' => 'turquoise',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'violeta',
                'cod_eng' => 'violet',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'prata',
                'cod_eng' => 'silver',
                'group' => 'cor',
                'group_eng' => 'color',
                'type' => 'cores',
            ],
            [
                'cod' => 'PP',
                'cod_eng' => 'XS',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'P',
                'cod_eng' => 'S',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'M',
                'cod_eng' => 'M',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'G',
                'cod_eng' => 'L',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'GG',
                'cod_eng' => 'XL',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'G1',
                'cod_eng' => 'XXL',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'G2',
                'cod_eng' => 'XXXL',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'G3',
                'cod_eng' => 'XXXXL',
                'group' => 'tamanho',
                'group_eng' => 'size',
                'type' => 'camiseta',
            ],
            [
                'cod' => 'ação',
                'cod_eng' => 'action',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'comédia',
                'cod_eng' => 'comedy',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'drama',
                'cod_eng' => 'drama',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'romance',
                'cod_eng' => 'romance',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'terror',
                'cod_eng' => 'horror',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'suspense',
                'cod_eng' => 'suspense',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'aventura',
                'cod_eng' => 'adventure',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'fantasia',
                'cod_eng' => 'fantasy',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'animação',
                'cod_eng' => 'animation',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'ficção científica',
                'cod_eng' => 'science fiction',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'documentário',
                'cod_eng' => 'documentary',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'crime',
                'cod_eng' => 'crime',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'história',
                'cod_eng' => 'history',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'biografia',
                'cod_eng' => 'biography',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'ação',
                'cod_eng' => 'action',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'comédia',
                'cod_eng' => 'comedy',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'drama',
                'cod_eng' => 'drama',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'romance',
                'cod_eng' => 'romance',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'terror',
                'cod_eng' => 'horror',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'suspense',
                'cod_eng' => 'suspense',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'aventura',
                'cod_eng' => 'adventure',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'fantasia',
                'cod_eng' => 'fantasy',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'animação',
                'cod_eng' => 'animation',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'ficção científica',
                'cod_eng' => 'science fiction',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'documentário',
                'cod_eng' => 'documentary',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'crime',
                'cod_eng' => 'crime',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'história',
                'cod_eng' => 'history',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'biografia',
                'cod_eng' => 'biography',
                'group' => 'gênero',
                'group_eng' => 'genre',
                'type' => 'filmes',
            ],
            [
                'cod' => 'margherita',
                'cod_eng' => 'margherita',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'calabresa',
                'cod_eng' => 'calabrese',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'pepperoni',
                'cod_eng' => 'pepperoni',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'frango com catupiry',
                'cod_eng' => 'chicken with catupiry',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'mussarela',
                'cod_eng' => 'mozzarella',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'portuguesa',
                'cod_eng' => 'portuguese',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'quatro queijos',
                'cod_eng' => 'four cheese',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'mista',
                'cod_eng' => 'mixed',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'atum',
                'cod_eng' => 'tuna',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'vegetariana',
                'cod_eng' => 'vegetarian',
                'group' => 'sabor',
                'group_eng' => 'flavor',
                'type' => 'pizza',
            ],
            [
                'cod' => 'alface',
                'cod_eng' => 'lettuce',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'tomate',
                'cod_eng' => 'tomato',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'queijo',
                'cod_eng' => 'cheese',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'presunto',
                'cod_eng' => 'ham',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'bacon',
                'cod_eng' => 'bacon',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'cebola',
                'cod_eng' => 'onion',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'molho barbecue',
                'cod_eng' => 'barbecue sauce',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'maionese',
                'cod_eng' => 'mayonnaise',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'ketchup',
                'cod_eng' => 'ketchup',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'mostarda',
                'cod_eng' => 'mustard',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'alface',
                'cod_eng' => 'lettuce',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'tomate',
                'cod_eng' => 'tomato',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'queijo',
                'cod_eng' => 'cheese',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'presunto',
                'cod_eng' => 'ham',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'bacon',
                'cod_eng' => 'bacon',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'cebola',
                'cod_eng' => 'onion',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'molho barbecue',
                'cod_eng' => 'barbecue sauce',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'maionese',
                'cod_eng' => 'mayonnaise',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'ketchup',
                'cod_eng' => 'ketchup',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
            [
                'cod' => 'mostarda',
                'cod_eng' => 'mustard',
                'group' => 'ingrediente',
                'group_eng' => 'ingredient',
                'type' => 'lanche',
            ],
        
            [
                'cod' => 'saúde',
                'cod_eng' => 'health',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'beleza',
                'cod_eng' => 'beauty',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'ferramentas',
                'cod_eng' => 'tools',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'eletrônicos',
                'cod_eng' => 'electronics',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'vestuário',
                'cod_eng' => 'clothing',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'alimentos',
                'cod_eng' => 'food',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'esportes',
                'cod_eng' => 'sports',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'casa e jardim',
                'cod_eng' => 'home and garden',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'livros',
                'cod_eng' => 'books',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'automotivo',
                'cod_eng' => 'automotive',
                'group' => 'departamento',
                'group_eng' => 'department',
                'type' => 'produto',
            ],
            [
                'cod' => 'camiseta',
                'cod_eng' => 't-shirt',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'camisa',
                'cod_eng' => 'shirt',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'vestido',
                'cod_eng' => 'dress',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'agasalho',
                'cod_eng' => 'sweatshirt',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'calça',
                'cod_eng' => 'pants',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'shorts',
                'cod_eng' => 'shorts',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'jaqueta',
                'cod_eng' => 'jacket',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'saia',
                'cod_eng' => 'skirt',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'blusa',
                'cod_eng' => 'blouse',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'macacão',
                'cod_eng' => 'jumpsuit',
                'group' => 'modelo',
                'group_eng' => 'model',
                'type' => 'roupa',
            ],
            [
                'cod' => 'colar',
                'cod_eng' => 'necklace',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'pulseira',
                'cod_eng' => 'bracelet',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'anel',
                'cod_eng' => 'ring',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'brinco',
                'cod_eng' => 'earring',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'óculos de sol',
                'cod_eng' => 'sunglasses',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'bolsa',
                'cod_eng' => 'bag',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'chapéu',
                'cod_eng' => 'hat',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'lenço',
                'cod_eng' => 'scarf',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'cinto',
                'cod_eng' => 'belt',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'boné',
                'cod_eng' => 'cap',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'acessório',
            ],
            [
                'cod' => 'metal',
                'cod_eng' => 'metal',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'madeira',
                'cod_eng' => 'wood',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'prata',
                'cod_eng' => 'silver',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'ouro',
                'cod_eng' => 'gold',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'bijuteria',
                'cod_eng' => 'costume jewelry',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'couro',
                'cod_eng' => 'leather',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'plástico',
                'cod_eng' => 'plastic',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'vidro',
                'cod_eng' => 'glass',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'cerâmica',
                'cod_eng' => 'ceramic',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'tecido',
                'cod_eng' => 'fabric',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'material',
            ],
            [
                'cod' => 'durável',
                'cod_eng' => 'durable',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'elegante',
                'cod_eng' => 'elegant',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'confortável',
                'cod_eng' => 'comfortable',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'inovador',
                'cod_eng' => 'innovative',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'versátil',
                'cod_eng' => 'versatile',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'eficiente',
                'cod_eng' => 'efficient',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'moderno',
                'cod_eng' => 'modern',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'estiloso',
                'cod_eng' => 'stylish',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'confiável',
                'cod_eng' => 'reliable',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'sustentável',
                'cod_eng' => 'sustainable',
                'group' => 'adjetivo',
                'group_eng' => 'adjective',
                'type' => 'produto',
            ],
            [
                'cod' => 'imagem',
                'cod_eng' => 'image',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'documento de texto',
                'cod_eng' => 'text document',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'planilha',
                'cod_eng' => 'spreadsheet',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'apresentação',
                'cod_eng' => 'presentation',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'arquivo compactado',
                'cod_eng' => 'compressed file',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'áudio',
                'cod_eng' => 'audio',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'vídeo',
                'cod_eng' => 'video',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'PDF',
                'cod_eng' => 'PDF',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'código fonte',
                'cod_eng' => 'source code',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'executável',
                'cod_eng' => 'executable',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'arquivo',
            ],
            [
                'cod' => 'educativo',
                'cod_eng' => 'educational',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'radical',
                'cod_eng' => 'extreme',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'aventura',
                'cod_eng' => 'adventure',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'comédia',
                'cod_eng' => 'comedy',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'romance',
                'cod_eng' => 'romance',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'terror',
                'cod_eng' => 'horror',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'fantasia',
                'cod_eng' => 'fantasy',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'ficção científica',
                'cod_eng' => 'science fiction',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'documentário',
                'cod_eng' => 'documentary',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'esporte',
                'cod_eng' => 'sports',
                'group' => 'categoria',
                'group_eng' => 'category',
                'type' => 'geral',
            ],
            [
                'cod' => 'videogame',
                'cod_eng' => 'videogame',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'bicicleta',
                'cod_eng' => 'bicycle',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'eletrodoméstico',
                'cod_eng' => 'home appliance',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'livro',
                'cod_eng' => 'book',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'celular',
                'cod_eng' => 'cell phone',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'roupa',
                'cod_eng' => 'clothing',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'lanche',
                'cod_eng' => 'snack',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'perfume',
                'cod_eng' => 'perfume',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'joia',
                'cod_eng' => 'jewelry',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
            [
                'cod' => 'instrumento musical',
                'cod_eng' => 'musical instrument',
                'group' => 'tipo',
                'group_eng' => 'type',
                'type' => 'produto',
            ],
        ];

        foreach ($tags as $tag) {
            //dd($tag); // Imprime os dados da tag para verificar

            Tag::create($tag); // Use essa linha para inserir a tag no banco de dados
        }
        
        
        
        
    }
}
